# Assignment 3

In [87]:
#Question-1
import numpy as np
arr = np.array(np.arange(2,50,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [26]:
#Question2
l1=[ ]
l2=[ ]
print("First list: ")
for i in range(0,5):
    x=int(input())
    l1.append(x);
print("Second list: ")
for i in range(0,5):
    x=int(input())
    l2.append(x);
l1=np.array(l1)
l2=np.array(l2)
print()
print(np.concatenate((l1,l2), axis=None))
print()
print("Sorted Array1: ",np.sort(l1))
print("Sorted Array2: ",np.sort(l2))

First list: 
1
2
7
5
3
Second list: 
7
6
3
9
10

[ 1  2  7  5  3  7  6  3  9 10]

Sorted Array1:  [1 2 3 5 7]
Sorted Array2:  [1 2 3 5 7]


In [85]:
#Question3
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("Dimensions:",arr.ndim)      #To find number of dimensions of an array.
print("Size:",arr.size)            #To find the size of an array.

Dimensions: 2
Size: 8


In [78]:
#Question4
arr=np.array([1,2,3])                #Suppose we have 1D array like this.
print(arr[:,np.newaxis])             #By applying np.newaxis one time we can convert arr into 2D.
print()
print()
print(np.expand_dims(arr,axis=0)) #By using np.expand_dims() also we can convert 1D into 2D
print()
print(np.expand_dims(arr,axis=1)) #By using np.expand_dims() also we can convert 1D into 2D

[[1]
 [2]
 [3]]


[[1 2 3]]

[[1]
 [2]
 [3]]


In [30]:
#Question5
A1=[[6,12,18],[24,30,36],[42,48,54]]
A2=[[7,14,21],[28,35,42],[49,56,72]]

print(np.vstack((A1,A2)))
print()
print(np.hstack((A1,A2)))

[[ 6 12 18]
 [24 30 36]
 [42 48 54]
 [ 7 14 21]
 [28 35 42]
 [49 56 72]]

[[ 6 12 18  7 14 21]
 [24 30 36 28 35 42]
 [42 48 54 49 56 72]]


In [86]:
#Question6
list1=[1,1,3,4,3,5]     #Suppose we have this kind of array having non-unique items.

print(set(list1))       #By applying set on this array we will get a set of unique items. 

print(len(set(list1)))           #By applying len() function we will get the number of unique items.

{1, 3, 4, 5}
4
